### ISSUE TITLE
Die Liste für Sprachen ist zu kurz

### ISSUE THREAD

**Issue by UlrichViefhaus** [thinkingstone/dsa-documents#5]
Wie bei vielen Gelehrten ist bei meinem Charakter die Liste der Sprachen und Schriften zu kurz.
In den Standardbögen habe ich Sprache und Dazugehörige Schrift in einem Feld kombiniert.
Z.B.:
Garethi / Kusliker Zeichen     12 / 4

Wäre eine solche Zusammenfassung auch möglich?

**Comment by thinkingstone** [comment]
Wenn man das PDF selbst ausfüllt, dann kann man natürlich eine Schrift und Sprache in einer Zeile zusammenfassen. 
Ich vermute Du meinst den Export aus der Helden-Software? Um eine Sprache und Schrift sinnvoll zusammenzufassen müsste man zu jeder Sprache genau eine Schrift zuordnen können. Das macht die Helden-Software nicht. Wenn ich mich richtig erinnere, dann sagt auch das Regelwerk, dass man eine Sprache in unterschiedlichen Schriften darstellen kann. Tulamidya kann z.B. in Kusliker Zeichen, Glyphen von Unau oder Tulamidya geschrieben werden. (WdS 31)
Daher sehe ich keine Möglichkeit, wie eine Srache und eine Schrift zusammengefasst werden kann. 

Was natürlich geht ist, den Sprachen mehr Platz auf Kosten der handwerklichen Talente zu spendieren. Dazu müsste man das Heldendokument.sla (bzw. PDF) ändern. 

Interessant wäre eine Statistik welche / wieviele Talente Helden so haben. Dann könnte man die Zeilenanzahl der Talente so anpassen, dass es für die meisten Helden passt.

**Comment by UlrichViefhaus** [comment]
Ja, ich meinte das den automatischen Export aus der Helden-Software.
Mit den verschiedenen Schriften hast du recht. Daran hatte ich gar nicht gedacht.

Ich hab mir die SLA mal angesehen und so bearbeitet, dass es für meine Gelehrten passt. Ich musste die Schriftarten aber durch die freien Versionen ersetzten, die ich auch für die DSA Latex Klasse verwende.
Danke für die Hinweise
